### ISSUE TITLE
ValueError: ['text_anchor'] are not supported arguments. Look at the documentation for supported arguments.

### ISSUE THREAD

**Issue by monkeycc** [P3rdigas/Crack-Excel#1]
```python
Exception in Tkinter callback
Traceback (most recent call last):
  File "E:\anaconda3\envs\PY38\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "E:\anaconda3\envs\PY38\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "main.py", line 318, in open_file_explorer
    self.files_listbox.insert("END", filename, text_anchor="w")
  File "E:\anaconda3\envs\PY38\lib\site-packages\CTkListbox\ctk_listbox.py", line 193, in insert
    self.buttons[index] = customtkinter.CTkButton(
  File "E:\anaconda3\envs\PY38\lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 52, in __init__
    super().__init__(master=master, bg_color=bg_color, width=width, height=height, **kwargs)
  File "E:\anaconda3\envs\PY38\lib\site-packages\customtkinter\windows\widgets\core_widget_classes\ctk_base_class.py", line 46, in __init__
    check_kwargs_empty(kwargs, raise_error=True)
  File "E:\anaconda3\envs\PY38\lib\site-packages\customtkinter\windows\widgets\utility\utility_functions.py", line 18, in check_kwargs_empty
    raise ValueError(f"{list(kwargs_dict.keys())} are not supported arguments. Look at the documentation for supported arguments.")
ValueError: ['text_anchor'] are not supported arguments. Look at the documentation for supported arguments.

```

**Comment by P3rdigas** [comment]
The argument 'text_anchor' doesn't exist in the current oficial version of customtkinter library. I had to change the library and i'm waiting for approval by the owner to implement that change. In this repository https://github.com/P3rdigas/CustomTkinter you can find the modified library. If you use poetry, the library will be automatically be install. Mean while this version of the application is very incomplete, i'm currently working in the GUI and discovering the best approaches for the app, so i recommend you to use the released version. Take in mind this program only removes passwords from workbooks, sheets and read-only files, files with password needed to be opened need a brute force tool and vba passwords are currently not supported yet.

**Comment by monkeycc** [comment]
thanks
We have found other frameworks and successfully resolved the issue



About this framework GUI
Suggested use
https://github.com/PySimpleGUI/PySimpleGUI

**Comment by P3rdigas** [comment]
Nice. Thanks for the suggestion, however i think i'm gonna stick with this framework, was the first i used, want to improve it and has a lot of my time invested in. Besides, the result of this framework feels more modern that PySimpleGui!
